config/routes.rb
Spree::Core::Engine.add_routes do
  resources :contacts, controller: 'contact_us/contacts', only: %i[new create]
  get 'contact-us' => 'contact_us/contacts#new', as: :contact_us
  post 'contact-us' => 'contact_us/contacts#create'
end

app/models/spree/contact_us/contact.rb
module Spree
  module ContactUs
    class Contact
      include ActiveModel::Conversion
      include ActiveModel::Validations

      attr_accessor :email, :message, :name, :subject

      EMAIL_REGEX = /\A
        [^\s@]+ # non-at-sign characters, at least one
          @     # at-sign
        [^\s.@] # non-at-sign and non-period character
        [^\s@]* # 0 or more non-at-sign characters, accepts any number of periods
         \.     # period
        [^\s@]* # 0 or more non-at-sign characters, accepts any number of periods
        [^\s.@] # non-at-sign and non-period character
      \z/x.freeze

      validates :email,   presence: true
      validates :email,   format: { with: EMAIL_REGEX }, if: -> { email.present? }
      validates :message, presence: true
      validates :name,    presence: { if: proc { SpreeContactUs.require_name } }
      validates :subject, presence: { if: proc { SpreeContactUs.require_subject } }

      def initialize(attributes = {})
        %i[email message name subject].each do |attribute|
          send("#{attribute}=", attributes[attribute]) if attributes&.key?(attribute)
        end
      end

      def save
        if valid?
          Spree::ContactUs::ContactMailer.contact_email(self).deliver_now
          return true
        end
        false
      end

      def persisted?
        false
      end
    end
  end
end

app/controllers/spree/contact_us/contacts_controller.rb
class Spree::ContactUs::ContactsController < Spree::StoreController
  helper 'spree/products'
  def create
    @contact = Spree::ContactUs::Contact.new(params[:contact_us_contact])

    if @contact.save
      if Spree::ContactUs::Config.contact_tracking_message.present?
        flash[:contact_tracking] = Spree::ContactUs::Config.contact_tracking_message
      end
      redirect_to(spree.root_path, notice: Spree.t('spree_contact_us.notices.success'))
    else
      render :new
    end
  end

  def new
    @contact = Spree::ContactUs::Contact.new
    @taxonomies = Spree::Taxonomy.includes(root: :children)
  end

  def meta_data_tags; end
  helper_method :meta_data_tags

  private

  def accurate_title
    Spree.t(:contact_us_title)
  end
end

app/views/spree/contact_us/contacts/new.html.erb
<%= render partial: 'spree/shared/error_messages', locals: { target: @contact } %>

<div class="contact-us">
  <div class="container">
    <div class="row">
      <div class="col-12 mb-lg-4 pt-lg-2 pb-lg-3 text-center text-lg-left">
        <h1 class="px-3 px-lg-0 pt-lg-1 my-5 contact-us-header"><%= Spree.t('spree_contact_us.header') %></h1>
      </div>
      <div class="col-12 col-lg-6 text-center text-lg-left">
        <div class="pt-2 pb-lg-1 mb-3 contact-us-subheader">
          <figure class="logo mx-auto mx-xl-0 pb-xl-1 mb-0 mb-xl-4">
            <%= image_tag Spree::Config[:logo], alt: current_store.name, class: 'w-25', title: current_store.name %>
          </figure>
        </div>
        <div><%= Spree.t('spree_contact_us.address_line1') %></div>
        <div class="mb-4 pb-2 pb-lg-0"><%= Spree.t('spree_contact_us.address_line2') %></div>
        <div><%= Spree.t('spree_contact_us.call_us') %>: <span class="green-text font-weight-bold"><%= Spree.t('spree_contact_us.call_us_number') %></span></div>
        <div><%= Spree.t('spree_contact_us.email') %>: <span class="green-text font-weight-bold"><%= current_store.mail_from_address %></span></div>
      </div>
      <div class="col-12 col-lg-6 mt-5 mt-lg-0">
        <div class="mt-4 mt-lg-2 mb-1 mb-lg-2 contact-us-subheader text-center text-lg-left">
          <%= Spree.t('spree_contact_us.left_title') %>
        </div>

        <%= form_for @contact, url: contact_us_path, html: { novalidate: '' } do |f| %>

          <% if SpreeContactUs.require_name %>
            <%= f.text_field :name, class: 'required col-12 mt-3 mb-1 mb-lg-2', placeholder: true %>
          <% end %>

          <%= f.email_field :email, class: 'required col-12 mt-3 mb-1 mb-lg-2', placeholder: true %>

          <% if SpreeContactUs.require_subject %>
            <%= f.text_field :subject, class: 'required col-12 mt-3 mb-1 mb-lg-2' %>
          <% end %>
            <%= f.text_area :message, class: 'required col-12 mt-3 mb-3', rows: 4, placeholder: Spree.t('spree_contact_us.message_placeholder') %>
          <div class="text-center text-lg-left mt-lg-1 mb-4">
            <%= f.submit Spree.t(:send), alt: Spree.t(:send), id: 'contact_us_contact_submit', title: Spree.t(:send),
                class: 'col-7 col-lg-4 mb-4 mb-lg-0 btn btn-primary text-uppercase font-weight-bold'
            %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>